spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache
    username: root
    password: mysql
  redis:
    host: 192.168.140.128
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D
debug: true